# Generated by Django 4.1.4 on 2022-12-10 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('free', '자유'), ('question', '문의')], default='free', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=1000)),
                ('writer', models.CharField(max_length=30)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
